version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "85:80"       # Map host port 85 to container port 80 (HTTP)
      - "8443:443"    # Map host port 8443 to container port 443 (HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the Nginx configuration file
      - /var/www/local.domain.com/:/var/www/local.domain.com/:ro  # Mount the web root directory
      - /etc/ssl/certs/local.domain.com.crt:/etc/ssl/certs/local.domain.com.crt:ro  # Mount the SSL certificate
      - /etc/ssl/private/local.domain.com.key:/etc/ssl/private/local.domain.com.key:ro  # Mount the SSL private key
    restart: unless-stopped
